# Name of your application. Used to uniquely configure containers.
service: umami

# Name of the container image.
image: nejos97/umami

# Deploy to these servers.
servers:
  web:
    - <%= ENV["DOMAIN_NAME"] %>

# Enable SSL auto certification via Let's Encrypt and allow for multiple apps on a single web server.
# Note: If using Cloudflare, set encryption mode in SSL/TLS setting to "Full" to enable CF-to-app encryption.
proxy:
  ssl: true
  host: <%= ENV["DOMAIN_NAME"] %>
  app_port: 3005
  healthcheck:
    interval: 5
    path: /api/heartbeat
    timeout: 5

# Credentials for your image host.
registry:
  username: nejos97

  # Always use an access token rather than real password (pulled from .kamal/secrets).
  password:
    - KAMAL_REGISTRY_PASSWORD

# Configure builder setup.
builder:
  arch: amd64
  context: .

# Inject ENV variables into containers (secrets come from .kamal/secrets).
env:
  clear:
    NODE_ENV: <%= ENV["NODE_ENV"] %>
  secret:
    - DATABASE_URL
    - APP_SECRET
